### ISSUE TITLE
上传错误

### ISSUE THREAD

**Issue by pincman** [GBCLStudio/fof-upload-qcloud#10]
一切配置都是正常的，但日志显示bucket不存在，同样的配置复制到picgo里是正常的

**Comment by Burial0268** [comment]
在中文论坛里面回复过了
这里简略的说一下:
桶名称是不包含"-"号后面那串数字的
只需要填入单单的同名称就行了
例如 你的桶在COS控制台显示是 example-1145141919810，填入插件内的桶名称仅为example

原帖回复 : https://discuss.flarum.org.cn/d/4058/54
