### ISSUE TITLE
Declaration of GBCLStudio\UploadExtQcloud\Templates\QcloudAudioTemplate::template(): string must be compatible with FoF\Upload\Contracts\TextFormatterTemplate::template()

### ISSUE THREAD

**Issue by bestony** [GBCLStudio/fof-upload-qcloud#11]
Fatal error: Declaration of GBCLStudio\UploadExtQcloud\Templates\QcloudAudioTemplate::template(): string must be compatible with FoF\Upload\Contracts\TextFormatterTemplate::template(): Illuminate\Contracts\View\View in /www/code/feishu.io/vendor/gbcl/fof-upload-qcloud/src/Templates/QcloudAudioTemplate.php on line 38

## version

  "fof/upload": "^1.3",

**Comment by Burial0268** [comment]
Upstream `FoF/Upload` updated the interface of extend, the extension hasn't been adapted yet

**Comment by Burial0268** [comment]
Theoretically fixed, you can try updating to `1.2.2` version to check it out
